# Generated by Django 3.2.9 on 2023-04-28 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('seats_capacity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('al_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting_loc', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrive_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')])),
                ('seats_left', models.IntegerField(blank=True)),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.aircrafts')),
                ('al', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airlines')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.IntegerField()),
                ('cls', models.IntegerField(choices=[(0, 'First'), (1, 'Business'), (2, 'Economics')])),
                ('price', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Booked'), (1, 'Available'), (2, 'Saved')])),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flights')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('b_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.IntegerField(choices=[(0, 'Visa'), (1, 'PayPal'), (2, 'Stripe'), (3, 'Apple Pay')])),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Finished'), (2, 'Refunding')])),
                ('f', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flights')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.seats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.AddField(
            model_name='aircrafts',
            name='al',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airlines'),
        ),
    ]
